apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-app-svc
spec:
  selector:
    app: django-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
